services:
  mongo:
    image: mongo
    restart: always
    env_file: .env
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: $MONGO_DB_DATABASE
      MONGO_INITDB_ROOT_USERNAME: $MONGO_DB_ROOT_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_DB_ROOT_PASSWORD
    volumes:
      - ./mongo/init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    networks:
      - backend

  mongo-express:
    depends_on:
      - mongo
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file: .env
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: $MONGO_DB_ADMIN_APP_USER
      ME_CONFIG_BASICAUTH_PASSWORD: $MONGO_DB_ADMIN_APP_PASSWORD
      ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGO_DB_ROOT_USER
      ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGO_DB_ROOT_PASSWORD
      ME_CONFIG_MONGODB_URL: mongodb://$MONGO_DB_ROOT_USER:$MONGO_DB_ROOT_PASSWORD@mongo:$MONGO_DB_PORT/
    networks:
      - frontend
      - backend

  server:
    depends_on:
      - mongo
    build: .
    entrypoint:
      - yarn
      - dev
    ports:
      - '8080:8080'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file: .env
    environment:
      - DB_NAME=$MONGO_DB_DATABASE
      - DB_USER=$MONGO_DB_USER
      - DB_PASSWORD=$MONGO_DB_PASSWORD
      - DB_PORT=$MONGO_DB_PORT
    networks:
      - frontend
      - backend

volumes:
  db:
networks:
  backend:
  frontend:
