services:
  mariadb_test:
    image: mariadb
    restart: always
    env_file: .env
    volumes:
      - ./maria/docker-entrypoint-initdb.d
    environment:
      MARIADB_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    networks:
      - backend

  server:
    restart: unless-stopped
    build: .
    entrypoint:
      - yarn
      - dev
    ports:
      - '8080:8080'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file: .env
    environment:
      # Uncomment when running MariaDB locally.
      - DB_HOST=mariadb_test
      # - DB_HOST=127.0.0.1
      - DB_PORT=3306
      - DB_NAME=$MYSQL_DATABASE
      - DB_USER=$MYSQL_USER
      - DB_PASSWORD=$MYSQL_PASSWORD
    networks:
      - backend

networks:
  backend:
